name: NightCity
main: cc.ranmc.city.Main
description: NightCity Forever
author: Ranica
version: Release 7.0
api-version: "1.21"
softdepend: [Vault,PlaceholderAPI,CatSeedLogin,ViaVersion]

permissions:

  city.admin:
    default: op
    description: 'Administrator only'

  city.user:
    default: true
    description: 'User only'

  city.vip:
    default: false
    description: 'VIP only'

  city.svip:
    default: false
    description: 'SVIP only'

  city.shift:
    default: true
    description: 'kit command'

commands:
  g:
    description: g
    usage: /<command>

  city:
    description: city
    usage: /<command>